// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Application: typeof import('./src/components/Application/Application.vue')['default']
    Idnex: typeof import('./src/components/Test/idnex.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/basic/SvgIcon/index.vue')['default']
    Test: typeof import('./src/components/ting.vue')['default']
    Text: typeof import('./src/components/text.vue')['default']
    Ting: typeof import('./src/components/ting.vue')['default']
  }
}

export {}
